server:
  addr: :8080

mysql:
  path: 127.0.0.1
  port: 3306
  config: charset=utf8&parseTime=True&loc=Local
  db-name: GDSC
  username: root
  password: fndmysql2022
  max-idle-conns: 10
  max-open-conns: 100
